### ISSUE TITLE
[1pt] Create a Game class in a separate .rb file.

### ISSUE THREAD

**Issue by GordonOtieno** [GordonOtieno/ruby-capstone#12]
- All Game class properties visible in the diagram should be defined and set up in the constructor method.
- Implement methods:
can_be_archived?() in the Game class
should override the method from the parent class
should return true if parent's method returns true AND if last_played_at is older than 2 years
otherwise, it should return false
- All data should be preserved by saving collections in .json files.

**Comment by Haadiiii** [comment]
https://github.com/GordonOtieno/ruby-capstone/pull/20
