### ISSUE TITLE
[1pt] Create a Book class in a separate .rb file.

### ISSUE THREAD

**Issue by GordonOtieno** [GordonOtieno/ruby-capstone#2]
- All Book class properties visible in the diagram should be defined and set up in the constructor method.
- can_be_archived?() in the Book class
should override the method from the parent class
should return true if parent's method returns true OR if cover_state equals to "bad"
otherwise, it should return false
-All data should be preserved by saving collections in .json files.

**Comment by Haadiiii** [comment]
https://github.com/GordonOtieno/ruby-capstone/pull/18
